# Retargeting to another Minecraft version means changing these five lines and nothing else.
# Current values for any version are listed at https://fabricmc.net/develop/
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9
fabric_api_version=0.115.0+1.21.1
loom_version=1.9-SNAPSHOT

mod_version=1.0.0
maven_group=dev.brandosandofan.spectune
archives_base_name=spectune

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
